### ISSUE TITLE
DevZen выходит раз в неделю

### ISSUE THREAD

**Issue by php-coder** [unchase/awesome-russian-it#11]
```diff
-Регулярность | Несколько выпусков в месяц
+Регулярность | Еженедельно
```

**Comment by php-coder** [comment]
P.S. а как контрибьютить в ваш репозиторий? Страница, судя по всему, генерируется, но не вижу исходников.

**Comment by unchase** [comment]
> P.S. а как контрибьютить в ваш репозиторий? Страница, судя по всему, генерируется, но не вижу исходников.

Исходники в private репозитории (само приложение в каталоге "utils"). Но для того, чтобы контрибьтить, править код не нужно. Есть файл [CONTRIBUTING.md](https://github.com/unchase/awesome-russian-it/blob/master/CONTRIBUTING.md), там описана структура файлов (как добавлять отдельные записи). Приложение пока меняет только содержимое `<span>`'ов
В планах добавить больше автоматизации (в том числе вычисление регулярности и продолжительности выпусков).
