### ISSUE TITLE
День и месяц перепутаны в поле "Релиз последнего эпизода"

### ISSUE THREAD

**Issue by php-coder** [unchase/awesome-russian-it#9]
Например, у подкаста "Паша + Слава":
```
Релиз последнего эпизода(Apple Podcasts) | 06.15.2020 00:12
```
Вместо 06.15.2020 должно быть 15.06.2020

**Comment by unchase** [comment]
Сейчас дата выводится в формате: "MM.dd.yyyy HH:mm"
Согласен, лучше выводить - "dd.MM.yyyy HH:mm"
